//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package no.nav.dok.brevdata.felles.v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Informasjon om hvordan bruker kan kontakte NAV før å følge opp saken
 * 
 * <p>Java class for Kontaktinformasjon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Kontaktinformasjon"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="returadresse" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Returadresse"/&gt;
 *         &lt;element name="postadresse" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Postadresse"/&gt;
 *         &lt;element name="besoksadresse" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Besoksadresse"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Kontaktinformasjon", propOrder = {

})
public class Kontaktinformasjon implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected Returadresse returadresse;
    @XmlElement(required = true)
    protected Postadresse postadresse;
    @XmlElement(required = true)
    protected Besoksadresse besoksadresse;

    /**
     * Gets the value of the returadresse property.
     * 
     * @return
     *     possible object is
     *     {@link Returadresse }
     *     
     */
    public Returadresse getReturadresse() {
        return returadresse;
    }

    /**
     * Sets the value of the returadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Returadresse }
     *     
     */
    public void setReturadresse(Returadresse value) {
        this.returadresse = value;
    }

    /**
     * Gets the value of the postadresse property.
     * 
     * @return
     *     possible object is
     *     {@link Postadresse }
     *     
     */
    public Postadresse getPostadresse() {
        return postadresse;
    }

    /**
     * Sets the value of the postadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Postadresse }
     *     
     */
    public void setPostadresse(Postadresse value) {
        this.postadresse = value;
    }

    /**
     * Gets the value of the besoksadresse property.
     * 
     * @return
     *     possible object is
     *     {@link Besoksadresse }
     *     
     */
    public Besoksadresse getBesoksadresse() {
        return besoksadresse;
    }

    /**
     * Sets the value of the besoksadresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Besoksadresse }
     *     
     */
    public void setBesoksadresse(Besoksadresse value) {
        this.besoksadresse = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Kontaktinformasjon)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Kontaktinformasjon that = ((Kontaktinformasjon) object);
        {
            Returadresse lhsReturadresse;
            lhsReturadresse = this.getReturadresse();
            Returadresse rhsReturadresse;
            rhsReturadresse = that.getReturadresse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "returadresse", lhsReturadresse), LocatorUtils.property(thatLocator, "returadresse", rhsReturadresse), lhsReturadresse, rhsReturadresse)) {
                return false;
            }
        }
        {
            Postadresse lhsPostadresse;
            lhsPostadresse = this.getPostadresse();
            Postadresse rhsPostadresse;
            rhsPostadresse = that.getPostadresse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "postadresse", lhsPostadresse), LocatorUtils.property(thatLocator, "postadresse", rhsPostadresse), lhsPostadresse, rhsPostadresse)) {
                return false;
            }
        }
        {
            Besoksadresse lhsBesoksadresse;
            lhsBesoksadresse = this.getBesoksadresse();
            Besoksadresse rhsBesoksadresse;
            rhsBesoksadresse = that.getBesoksadresse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "besoksadresse", lhsBesoksadresse), LocatorUtils.property(thatLocator, "besoksadresse", rhsBesoksadresse), lhsBesoksadresse, rhsBesoksadresse)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Returadresse theReturadresse;
            theReturadresse = this.getReturadresse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "returadresse", theReturadresse), currentHashCode, theReturadresse);
        }
        {
            Postadresse thePostadresse;
            thePostadresse = this.getPostadresse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "postadresse", thePostadresse), currentHashCode, thePostadresse);
        }
        {
            Besoksadresse theBesoksadresse;
            theBesoksadresse = this.getBesoksadresse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "besoksadresse", theBesoksadresse), currentHashCode, theBesoksadresse);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Returadresse theReturadresse;
            theReturadresse = this.getReturadresse();
            strategy.appendField(locator, this, "returadresse", buffer, theReturadresse);
        }
        {
            Postadresse thePostadresse;
            thePostadresse = this.getPostadresse();
            strategy.appendField(locator, this, "postadresse", buffer, thePostadresse);
        }
        {
            Besoksadresse theBesoksadresse;
            theBesoksadresse = this.getBesoksadresse();
            strategy.appendField(locator, this, "besoksadresse", buffer, theBesoksadresse);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        _other.returadresse = ((this.returadresse == null)?null:this.returadresse.newCopyBuilder(_other));
        _other.postadresse = ((this.postadresse == null)?null:this.postadresse.newCopyBuilder(_other));
        _other.besoksadresse = ((this.besoksadresse == null)?null:this.besoksadresse.newCopyBuilder(_other));
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final Kontaktinformasjon _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree returadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("returadresse"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(returadressePropertyTree!= null):((returadressePropertyTree == null)||(!returadressePropertyTree.isLeaf())))) {
            _other.returadresse = ((this.returadresse == null)?null:this.returadresse.newCopyBuilder(_other, returadressePropertyTree, _propertyTreeUse));
        }
        final PropertyTree postadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("postadresse"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(postadressePropertyTree!= null):((postadressePropertyTree == null)||(!postadressePropertyTree.isLeaf())))) {
            _other.postadresse = ((this.postadresse == null)?null:this.postadresse.newCopyBuilder(_other, postadressePropertyTree, _propertyTreeUse));
        }
        final PropertyTree besoksadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("besoksadresse"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(besoksadressePropertyTree!= null):((besoksadressePropertyTree == null)||(!besoksadressePropertyTree.isLeaf())))) {
            _other.besoksadresse = ((this.besoksadresse == null)?null:this.besoksadresse.newCopyBuilder(_other, besoksadressePropertyTree, _propertyTreeUse));
        }
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final Kontaktinformasjon _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final Kontaktinformasjon _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final Kontaktinformasjon _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final Kontaktinformasjon _storedValue;
        private Returadresse.Builder<Builder<_B>> returadresse;
        private Postadresse.Builder<Builder<_B>> postadresse;
        private Besoksadresse.Builder<Builder<_B>> besoksadresse;

        public Builder(final _B _parentBuilder, final Kontaktinformasjon _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.returadresse = ((_other.returadresse == null)?null:_other.returadresse.newCopyBuilder(this));
                    this.postadresse = ((_other.postadresse == null)?null:_other.postadresse.newCopyBuilder(this));
                    this.besoksadresse = ((_other.besoksadresse == null)?null:_other.besoksadresse.newCopyBuilder(this));
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final Kontaktinformasjon _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree returadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("returadresse"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(returadressePropertyTree!= null):((returadressePropertyTree == null)||(!returadressePropertyTree.isLeaf())))) {
                        this.returadresse = ((_other.returadresse == null)?null:_other.returadresse.newCopyBuilder(this, returadressePropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree postadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("postadresse"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(postadressePropertyTree!= null):((postadressePropertyTree == null)||(!postadressePropertyTree.isLeaf())))) {
                        this.postadresse = ((_other.postadresse == null)?null:_other.postadresse.newCopyBuilder(this, postadressePropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree besoksadressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("besoksadresse"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(besoksadressePropertyTree!= null):((besoksadressePropertyTree == null)||(!besoksadressePropertyTree.isLeaf())))) {
                        this.besoksadresse = ((_other.besoksadresse == null)?null:_other.besoksadresse.newCopyBuilder(this, besoksadressePropertyTree, _propertyTreeUse));
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends Kontaktinformasjon >_P init(final _P _product) {
            _product.returadresse = ((this.returadresse == null)?null:this.returadresse.build());
            _product.postadresse = ((this.postadresse == null)?null:this.postadresse.build());
            _product.besoksadresse = ((this.besoksadresse == null)?null:this.besoksadresse.build());
            return _product;
        }

        /**
         * Sets the new value of "returadresse" (any previous value will be replaced)
         * 
         * @param returadresse
         *     New value of the "returadresse" property.
         */
        public Builder<_B> withReturadresse(final Returadresse returadresse) {
            this.returadresse = ((returadresse == null)?null:new Returadresse.Builder<Builder<_B>>(this, returadresse, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "returadresse" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Returadresse.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "returadresse" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Returadresse.Builder#end()} to return to the current builder.
         */
        public Returadresse.Builder<? extends Builder<_B>> withReturadresse() {
            return this.returadresse = new Returadresse.Builder<Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "postadresse" (any previous value will be replaced)
         * 
         * @param postadresse
         *     New value of the "postadresse" property.
         */
        public Builder<_B> withPostadresse(final Postadresse postadresse) {
            this.postadresse = ((postadresse == null)?null:new Postadresse.Builder<Builder<_B>>(this, postadresse, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "postadresse" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Postadresse.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "postadresse" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Postadresse.Builder#end()} to return to the current builder.
         */
        public Postadresse.Builder<? extends Builder<_B>> withPostadresse() {
            return this.postadresse = new Postadresse.Builder<Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "besoksadresse" (any previous value will be replaced)
         * 
         * @param besoksadresse
         *     New value of the "besoksadresse" property.
         */
        public Builder<_B> withBesoksadresse(final Besoksadresse besoksadresse) {
            this.besoksadresse = ((besoksadresse == null)?null:new Besoksadresse.Builder<Builder<_B>>(this, besoksadresse, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "besoksadresse" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Besoksadresse.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "besoksadresse" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.Besoksadresse.Builder#end()} to return to the current builder.
         */
        public Besoksadresse.Builder<? extends Builder<_B>> withBesoksadresse() {
            return this.besoksadresse = new Besoksadresse.Builder<Builder<_B>>(this, null, false);
        }

        @Override
        public Kontaktinformasjon build() {
            if (_storedValue == null) {
                return this.init(new Kontaktinformasjon());
            } else {
                return ((Kontaktinformasjon) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private Returadresse.Selector<TRoot, Selector<TRoot, TParent>> returadresse = null;
        private Postadresse.Selector<TRoot, Selector<TRoot, TParent>> postadresse = null;
        private Besoksadresse.Selector<TRoot, Selector<TRoot, TParent>> besoksadresse = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.returadresse!= null) {
                products.put("returadresse", this.returadresse.init());
            }
            if (this.postadresse!= null) {
                products.put("postadresse", this.postadresse.init());
            }
            if (this.besoksadresse!= null) {
                products.put("besoksadresse", this.besoksadresse.init());
            }
            return products;
        }

        public Returadresse.Selector<TRoot, Selector<TRoot, TParent>> returadresse() {
            return ((this.returadresse == null)?this.returadresse = new Returadresse.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "returadresse"):this.returadresse);
        }

        public Postadresse.Selector<TRoot, Selector<TRoot, TParent>> postadresse() {
            return ((this.postadresse == null)?this.postadresse = new Postadresse.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "postadresse"):this.postadresse);
        }

        public Besoksadresse.Selector<TRoot, Selector<TRoot, TParent>> besoksadresse() {
            return ((this.besoksadresse == null)?this.besoksadresse = new Besoksadresse.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "besoksadresse"):this.besoksadresse);
        }

    }

}
