//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package no.nav.dok.brevdata.felles.v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import no.nav.dok.brevdata.felles.v1.simpletypes.AktoerType;
import no.nav.dok.brevdata.felles.v1.simpletypes.Spraakkode;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Gydig mottaker type
 * 
 * <p>Java class for Organisasjon complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Organisasjon"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Mottaker"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Organisasjon")
public class Organisasjon
    extends Mottaker
    implements Equals, HashCode, ToString
{


    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Organisasjon)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    @Override
    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final Aktoer _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Mottaker _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Organisasjon _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    @Override
    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final Aktoer _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Mottaker _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Organisasjon _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final Aktoer _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final Mottaker _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final Organisasjon _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final Aktoer _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final Mottaker _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final Organisasjon _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >
        extends Mottaker.Builder<_B>
        implements Buildable
    {


        public Builder(final _B _parentBuilder, final Organisasjon _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
            }
        }

        public Builder(final _B _parentBuilder, final Organisasjon _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
            }
        }

        protected<_P extends Organisasjon >_P init(final _P _product) {
            return super.init(_product);
        }

        /**
         * Sets the new value of "kortNavn" (any previous value will be replaced)
         * 
         * @param kortNavn
         *     New value of the "kortNavn" property.
         */
        @Override
        public Builder<_B> withKortNavn(final String kortNavn) {
            super.withKortNavn(kortNavn);
            return this;
        }

        /**
         * Sets the new value of "spraakkode" (any previous value will be replaced)
         * 
         * @param spraakkode
         *     New value of the "spraakkode" property.
         */
        @Override
        public Builder<_B> withSpraakkode(final Spraakkode spraakkode) {
            super.withSpraakkode(spraakkode);
            return this;
        }

        /**
         * Sets the new value of "mottakeradresse" (any previous value will be replaced)
         * 
         * @param mottakeradresse
         *     New value of the "mottakeradresse" property.
         */
        @Override
        public Builder<_B> withMottakeradresse(final Adresse mottakeradresse) {
            super.withMottakeradresse(mottakeradresse);
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        @Override
        public Builder<_B> withBerik(final Boolean berik) {
            super.withBerik(berik);
            return this;
        }

        /**
         * Sets the new value of "id" (any previous value will be replaced)
         * 
         * @param id
         *     New value of the "id" property.
         */
        @Override
        public Builder<_B> withId(final String id) {
            super.withId(id);
            return this;
        }

        /**
         * Sets the new value of "typeKode" (any previous value will be replaced)
         * 
         * @param typeKode
         *     New value of the "typeKode" property.
         */
        @Override
        public Builder<_B> withTypeKode(final AktoerType typeKode) {
            super.withTypeKode(typeKode);
            return this;
        }

        /**
         * Sets the new value of "navn" (any previous value will be replaced)
         * 
         * @param navn
         *     New value of the "navn" property.
         */
        @Override
        public Builder<_B> withNavn(final String navn) {
            super.withNavn(navn);
            return this;
        }

        @Override
        public Organisasjon build() {
            if (_storedValue == null) {
                return this.init(new Organisasjon());
            } else {
                return ((Organisasjon) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends Mottaker.Selector<TRoot, TParent>
    {


        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            return products;
        }

    }

}
