//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package no.nav.dok.brevdata.felles.v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Gydig mottaker type
 * 
 * <p>Java class for Returadresse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Returadresse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}AdresseEnhet"&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Returadresse")
public class Returadresse
    extends AdresseEnhet
    implements Equals, HashCode, ToString
{


    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Returadresse)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    @Override
    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final NavEnhet _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final AdresseEnhet _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Returadresse _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    @Override
    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final NavEnhet _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final AdresseEnhet _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Returadresse _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final NavEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final AdresseEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final Returadresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final NavEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final AdresseEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final Returadresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >
        extends AdresseEnhet.Builder<_B>
        implements Buildable
    {


        public Builder(final _B _parentBuilder, final Returadresse _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
            }
        }

        public Builder(final _B _parentBuilder, final Returadresse _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
            }
        }

        protected<_P extends Returadresse >_P init(final _P _product) {
            return super.init(_product);
        }

        /**
         * Sets the new value of "kontaktTelefonnummer" (any previous value will be replaced)
         * 
         * @param kontaktTelefonnummer
         *     New value of the "kontaktTelefonnummer" property.
         */
        @Override
        public Builder<_B> withKontaktTelefonnummer(final String kontaktTelefonnummer) {
            super.withKontaktTelefonnummer(kontaktTelefonnummer);
            return this;
        }

        /**
         * Sets the new value of "adresse" (any previous value will be replaced)
         * 
         * @param adresse
         *     New value of the "adresse" property.
         */
        @Override
        public Builder<_B> withAdresse(final NorskPostadresse adresse) {
            super.withAdresse(adresse);
            return this;
        }

        /**
         * Returns a new builder to build the value of the "adresse" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NorskPostadresse.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "adresse" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NorskPostadresse.Builder#end()} to return to the current builder.
         */
        public NorskPostadresse.Builder<? extends Builder<_B>> withAdresse() {
            return ((NorskPostadresse.Builder<? extends Builder<_B>> ) super.withAdresse());
        }

        /**
         * Sets the new value of "enhetsId" (any previous value will be replaced)
         * 
         * @param enhetsId
         *     New value of the "enhetsId" property.
         */
        @Override
        public Builder<_B> withEnhetsId(final String enhetsId) {
            super.withEnhetsId(enhetsId);
            return this;
        }

        /**
         * Sets the new value of "enhetsNavn" (any previous value will be replaced)
         * 
         * @param enhetsNavn
         *     New value of the "enhetsNavn" property.
         */
        @Override
        public Builder<_B> withEnhetsNavn(final String enhetsNavn) {
            super.withEnhetsNavn(enhetsNavn);
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        @Override
        public Builder<_B> withBerik(final Boolean berik) {
            super.withBerik(berik);
            return this;
        }

        @Override
        public Returadresse build() {
            if (_storedValue == null) {
                return this.init(new Returadresse());
            } else {
                return ((Returadresse) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends AdresseEnhet.Selector<TRoot, TParent>
    {


        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            return products;
        }

    }

}
