<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>no.nav.dok</groupId>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.tjenester</groupId>
	<artifactId>dok-nav-dokumentproduksjon-v3-tjenestespesifikasjon</artifactId>
	<version>${revision}</version>

	<properties>
		<wsdl.directory>src/main/resources/wsdl/no/nav/tjeneste/virksomhet/dokumentproduksjon/v3</wsdl.directory>
		<jaxb2-fluent-api.version>3.0</jaxb2-fluent-api.version>
		<jaxb2-basics-annotate.version>1.1.0</jaxb2-basics-annotate.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.patrodyne.jvnet</groupId>
			<artifactId>hisrc-basicjaxb-plugins</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.patrodyne.jvnet</groupId>
			<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>jakarta.jws</groupId>
			<artifactId>jakarta.jws-api</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.ws</groupId>
			<artifactId>jakarta.xml.ws-api</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-codegen-plugin</artifactId>
				<executions>
					<execution>
						<id>wsdl-to-java</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsdl2java</goal>
						</goals>
						<configuration>
							<defaultOptions>
								<extraargs>
									<extraarg>-xjc-Xannotate</extraarg>
									<extraarg>-client</extraarg>
								</extraargs>
							</defaultOptions>
							<wsdlOptions>
								<wsdlOption>
									<wsdl>${wsdl.directory}/Binding.wsdl</wsdl>
									<wsdlLocation>
										classpath:wsdl/no/nav/tjeneste/virksomhet/dokumentproduksjon/v3/Binding.wsdl
									</wsdlLocation>
									<serviceName>Dokumentproduksjon_v3</serviceName>
									<bindingFiles>
										<bindingFile>${basedir}/src/main/bindings/informasjon.xjb</bindingFile>
										<bindingFile>${basedir}/src/main/bindings/meldinger.xjb</bindingFile>
										<bindingFile>${basedir}/src/main/bindings/Binding.xjb</bindingFile>
									</bindingFiles>
								</wsdlOption>
							</wsdlOptions>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.patrodyne.jvnet</groupId>
						<artifactId>hisrc-basicjaxb-plugins</artifactId>
						<version>${hisrc-jaxb.version}</version>
					</dependency>
					<dependency>
						<groupId>org.patrodyne.jvnet</groupId>
						<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
						<version>${hisrc-jaxb.version}</version>
					</dependency>
				</dependencies>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>