<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>no.nav.dok</groupId>
	<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
	<version>${revision}</version>
	<name>dok-legacy-tjenestespesifikasjoner</name>
	<packaging>pom</packaging>

	<modules>
		<module>metaforce-general-service-tjenestespesifikasjon</module>
		<module>dok-brevdata-felles</module>
		<module>dokumentbehandling-tjenestespesifikasjon</module>
		<module>behandledokumentredigering-tjenestespesifikasjon</module>
		<module>dok-nav-fim-dokumentproduksjon-v2-tjenestespesifikasjon</module>
		<module>dok-nav-dokumentproduksjon-v3-tjenestespesifikasjon</module>
		<module>nav-virksomhet-dokumentstatusoppdatert-v1-meldingsdefinisjon</module>
		<module>loggmottak-tjenestespesifikasjon</module>
		<module>nav-journal-tjenestespesifikasjon</module>
	</modules>

	<distributionManagement>
		<repository>
			<id>ghcr</id>
			<url>https://maven.pkg.github.com/navikt/dok-legacy-tjenestespesifikasjoner</url>
		</repository>
	</distributionManagement>

	<properties>
		<revision>1.0-SNAPSHOT</revision>

		<java.version>17</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<jaxb2-basics.version>0.13.1</jaxb2-basics.version>
		<jaxb-fluent-api.version>2.1.8</jaxb-fluent-api.version>
		<jakarta.xml.version>2.3.3</jakarta.xml.version>
		<jakarta.xml.ws-api.version>2.3.3</jakarta.xml.ws-api.version>
		<jakarta.jws-api.version>2.1.0</jakarta.jws-api.version>
		<!-- plugins -->
		<maven-toolchains-plugin.version>3.1.0</maven-toolchains-plugin.version>
		<cxf-codegen-plugin.version>3.5.5</cxf-codegen-plugin.version>
		<maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
		<maven-resources-plugin.version>3.3.0</maven-resources-plugin.version>
		<maven-clean-plugin.version>3.2.0</maven-clean-plugin.version>
		<maven-install-plugin.version>3.1.0</maven-install-plugin.version>
		<maven-jar-plugin.version>3.3.0</maven-jar-plugin.version>
		<maven-dependency-plugin.version>3.5.0</maven-dependency-plugin.version>
		<maven-deploy-plugin.version>3.0.0</maven-deploy-plugin.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.jvnet.jaxb2_commons</groupId>
				<artifactId>jaxb2-basics</artifactId>
				<version>${jaxb2-basics.version}</version>
				<optional>true</optional>
				<exclusions>
					<exclusion>
						<groupId>commons-logging</groupId>
						<artifactId>commons-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.jvnet.jaxb2_commons</groupId>
				<artifactId>jaxb2-basics-runtime</artifactId>
				<version>${jaxb2-basics.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.xml.bind</groupId>
				<artifactId>jakarta.xml.bind-api</artifactId>
				<version>${jakarta.xml.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.jws</groupId>
				<artifactId>jakarta.jws-api</artifactId>
				<version>${jakarta.jws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.xml.ws</groupId>
				<artifactId>jakarta.xml.ws-api</artifactId>
				<version>${jakarta.xml.ws-api.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.cxf</groupId>
					<artifactId>cxf-codegen-plugin</artifactId>
					<version>${cxf-codegen-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>${maven-resources-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<version>${maven-clean-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>${maven-install-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>${maven-dependency-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>${maven-deploy-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-toolchains-plugin</artifactId>
					<version>${maven-toolchains-plugin.version}</version>
					<executions>
						<execution>
							<goals>
								<goal>toolchain</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<toolchains>
							<jdk>
								<version>${java.version}</version>
								<vendor>openjdk</vendor>
							</jdk>
						</toolchains>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
