<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<groupId>no.nav.dok</groupId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.dok.metaforcemal</groupId>
	<artifactId>brevdata-felles</artifactId>
	<version>${revision}</version>
	<name>${project.artifactId}</name>

	<properties>
		<maven-release-plugin.version>3.0.0</maven-release-plugin.version>
		<maven-assembly-plugin.version>2.5.3</maven-assembly-plugin.version>
		<wagon-webdav-jackrabbitt.version>1.0</wagon-webdav-jackrabbitt.version>

		<jaxb2-basics.version>0.6.5</jaxb2-basics.version>
		<jaxb2-maven-plugin.version>0.13.2</jaxb2-maven-plugin.version>
		<jaxb2-rich-contract-plugin.version>1.18.0</jaxb2-rich-contract-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.jvnet.jaxb2_commons</groupId>
			<artifactId>jaxb2-basics</artifactId>
			<version>${jaxb2-basics.version}</version>
		</dependency>
		<dependency>
			<groupId>net.codesup.util</groupId>
			<artifactId>jaxb2-rich-contract-plugin</artifactId>
			<version>${jaxb2-rich-contract-plugin.version}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>${wagon-webdav-jackrabbitt.version}</version>
			</extension>
		</extensions>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>${maven-assembly-plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<artifactId>maven-release-plugin</artifactId>
				<version>${maven-release-plugin.version}</version>
				<configuration>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<goals>deploy</goals>
					<preparationGoals>clean install</preparationGoals>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<failOnError>false</failOnError>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<id>xsd</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>xsd</classifier>
							<includes>
								<include>navfelles/*.xsd</include>
							</includes>
						</configuration>
					</execution>
					<execution>
						<id>jaxb</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>jaxb</classifier>
							<includes>
								<include>no/nav/dok/**</include>
							</includes>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>${jaxb2-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>generate-jaxb-xsd.navfelles</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>src/main/resources/navfelles</schemaDirectory>
							<generateDirectory>${project.build.directory}/generated-sources/</generateDirectory>
							<strict>false</strict>
							<plugins>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics</artifactId>
									<version>${jaxb2-basics.version}</version>
								</plugin>
								<plugin>
									<groupId>org.jvnet.jaxb2_commons</groupId>
									<artifactId>jaxb2-basics-annotate</artifactId>
									<version>${jaxb2-basics.version}</version>
								</plugin>
								<plugin>
									<groupId>net.codesup.util</groupId>
									<artifactId>jaxb2-rich-contract-plugin</artifactId>
									<version>${jaxb2-rich-contract-plugin.version}</version>
								</plugin>
							</plugins>
							<args>
								<arg>-Xannotate</arg>
								<arg>-Xequals</arg>
								<arg>-XhashCode</arg>
								<arg>-XtoString</arg>
								<arg>-Xfluent-builder</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>