<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<groupId>no.nav.dok</groupId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.tjenester.brevogarkiv</groupId>
	<artifactId>behandledokumentredigering-tjenestespesifikasjon</artifactId>
	<version>${revision}</version>

	<properties>
		<wsdl.directory>src/main/resources/wsdl/no/nav/tjeneste/domene/brevogarkiv/behandledokumentredigering/v1</wsdl.directory>
	</properties>

	<dependencies>
		<dependency>
			<groupId>jakarta.xml.ws</groupId>
			<artifactId>jakarta.xml.ws-api</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack dependencies</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includes>**/*.xsd</includes>
							<outputDirectory>${project.build.directory}/classes</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-codegen-plugin</artifactId>
				<executions>
					<execution>
						<id>wsdl-to-java</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsdl2java</goal>
						</goals>
						<configuration>
							<defaultOptions>
								<extraargs>
									<extraarg>-xjc-XfluentAPI</extraarg>
								</extraargs>
							</defaultOptions>
							<wsdlOptions>
								<wsdlOption>
									<wsdl>${wsdl.directory}/behandledokumentredigering.wsdl</wsdl>
									<bindingFiles>
										<bindingFile>src/main/resources/bindings.xml</bindingFile>
									</bindingFiles>
								</wsdlOption>
							</wsdlOptions>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>org.patrodyne.jvnet</groupId>
						<artifactId>hisrc-basicjaxb-plugins</artifactId>
						<version>${hisrc-jaxb.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

</project>
