<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>no.nav.dok</groupId>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.tjenestespesifikasjoner</groupId>
	<artifactId>nav-varsel-inn</artifactId>
	<version>${revision}</version>

	<dependencies>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.patrodyne.jvnet</groupId>
				<artifactId>hisrc-higherjaxb30-maven-plugin</artifactId>
				<version>2.1.0</version>
				<executions>
					<execution>
						<id>generate-jaxb-sdp</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>${project.basedir}/src/main/resources/xsd/</schemaDirectory>
							<bindingDirectory>${project.basedir}/src/main/resources/xjb/</bindingDirectory>
							<generateDirectory>${project.build.directory}/generated-sources/xjc-xsd</generateDirectory>
							<strict>false</strict>
							<plugins>
								<dependency>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-basicjaxb-plugins</artifactId>
								</dependency>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
									<version>${hisrc-jaxb.version}</version>
								</plugin>
							</plugins>
							<args>
								<extraarg>-XfluentAPI</extraarg>
								<arg>-Xannotate</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
			<resource>
				<directory>${wsdl.directory}</directory>
				<targetPath>wsdl</targetPath>
			</resource>
		</resources>
	</build>
</project>
