<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>no.nav.dok</groupId>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.meldinger.virksomhet</groupId>
	<artifactId>melding-virksomhet-dokdistfordeling</artifactId>
	<version>${revision}</version>

	<dependencies>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.patrodyne.jvnet</groupId>
				<artifactId>hisrc-higherjaxb40-maven-plugin</artifactId>
				<configuration>
					<strict>false</strict>
					<plugins>
						<dependency>
							<groupId>org.patrodyne.jvnet</groupId>
							<artifactId>hisrc-basicjaxb-plugins</artifactId>
						</dependency>
						<plugin>
							<groupId>org.patrodyne.jvnet</groupId>
							<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
						</plugin>
					</plugins>
					<args>
						<arg>-Xannotate</arg>
						<arg>-XfluentAPI</arg>
					</args>
				</configuration>
				<executions>
					<execution>
						<id>generate-jaxb-dokdistfordeling-qdist008-in</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.nav.meldinger.virksomhet.dokdistfordeling.qdist008.in</generatePackage>
							<schemaDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/xsd/qdist008/in/
							</schemaDirectory>
							<bindingDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/bindings/qdist008/in/
							</bindingDirectory>
							<generateDirectory>${project.build.directory}/no/nav/meldinger/virksomhet/dokdistfordeling/qdist008/in
							</generateDirectory>
						</configuration>
					</execution>
					<execution>
						<id>generate-jaxb-dokdistfordeling-qdist008-out</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.nav.meldinger.virksomhet.dokdistfordeling.qdist008.out</generatePackage>
							<schemaDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/xsd/qdist008/out/</schemaDirectory>
							<bindingDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/bindings/qdist008/out/
							</bindingDirectory>
							<generateDirectory>${project.build.directory}/no/nav/meldinger/virksomhet/dokdistfordeling/qdist008/out
							</generateDirectory>
						</configuration>
					</execution>
					<execution>
						<id>generate-jaxb-dokdistfordeling-qdist012</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<generatePackage>no.nav.meldinger.virksomhet.dokdistfordeling.qdist012</generatePackage>
							<schemaDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/xsd/qdist012/
							</schemaDirectory>
							<bindingDirectory>src/main/resources/no/nav/meldinger/virksomhet/dokdistfordeling/bindings/qdist012/
							</bindingDirectory>
							<generateDirectory>${project.build.directory}/no/nav/meldinger/virksomhet/dokdistfordeling/qdist012
							</generateDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>