<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
		<groupId>no.nav.dok</groupId>
		<version>${revision}</version>
	</parent>

	<groupId>no.nav.dok.metaforcemal</groupId>
	<artifactId>dok-brevdata-felles</artifactId>
	<version>${revision}</version>
	<name>dok-brevdata-felles</name>

	<properties>
		<jaxb40-maven-plugin.version>0.16.1</jaxb40-maven-plugin.version>
		<jakarta.xml.bind-api.version>4.0.0</jakarta.xml.bind-api.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>${jakarta.xml.bind-api.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>com.helger.maven</groupId>
				<artifactId>jaxb40-maven-plugin</artifactId>
				<version>${jaxb40-maven-plugin.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>