<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nav.no/tjeneste/domene/brevogarkiv/behandledokumentredigering/v1/meldinger"
	xmlns:tns="http://nav.no/tjeneste/domene/brevogarkiv/behandledokumentredigering/v1/meldinger"
	xmlns:behandledokumentredigering="http://nav.no/tjeneste/domene/brevogarkiv/behandledokumentredigering/v1/informasjon">

	<xs:import namespace="http://nav.no/tjeneste/domene/brevogarkiv/behandledokumentredigering/v1/informasjon" schemaLocation="../informasjon/informasjon.xsd"/>

	<xs:complexType name="DokumentStatusEndretRequest">
		<xs:sequence>
			<xs:element name="instanceId" type="xs:long"/>
			<xs:element name="dokumentStatus" type="behandledokumentredigering:DokumentStatus"/>
			<xs:element name="saksbehandlerId" type="xs:string"/>
			<xs:element name="jobId" type="xs:long" minOccurs="0"/>
			<xs:element name="docId" type="xs:long" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DokumentStatusEndretResponse">
		<xs:sequence/>
	</xs:complexType>
	<xs:complexType name="PingRequest">
		<xs:sequence/>
	</xs:complexType>
	<xs:complexType name="PingResponse">
		<xs:sequence/>
	</xs:complexType>
	
</xs:schema>