<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>dok-legacy-tjenestespesifikasjoner</artifactId>
        <groupId>no.nav.dok</groupId>
        <version>${revision}</version>
    </parent>

    <groupId>no.nav.meldinger.virksomhet</groupId>
    <artifactId>nav-virksomhet-dokumentstatusoppdatert-v1-meldingsdefinisjon</artifactId>
    <version>${revision}</version>

	<build>
		<plugins>
			<plugin>
				<groupId>com.helger.maven</groupId>
				<artifactId>jaxb40-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>