//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * En NAV-enhet med telefonnummer og adresse
 * 
 * <p>Java class for AdresseEnhet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresseEnhet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}NavEnhet"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kontaktTelefonnummer" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *         &lt;element name="adresse" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}NorskPostadresse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresseEnhet", propOrder = {
    "kontaktTelefonnummer",
    "adresse"
})
@XmlSeeAlso({
    Returadresse.class,
    Postadresse.class,
    Besoksadresse.class
})
public abstract class AdresseEnhet
    extends NavEnhet
    implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String kontaktTelefonnummer;
    @XmlElement(required = true)
    protected NorskPostadresse adresse;

    /**
     * Gets the value of the kontaktTelefonnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontaktTelefonnummer() {
        return kontaktTelefonnummer;
    }

    /**
     * Sets the value of the kontaktTelefonnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontaktTelefonnummer(String value) {
        this.kontaktTelefonnummer = value;
    }

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link NorskPostadresse }
     *     
     */
    public NorskPostadresse getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link NorskPostadresse }
     *     
     */
    public void setAdresse(NorskPostadresse value) {
        this.adresse = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AdresseEnhet)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final AdresseEnhet that = ((AdresseEnhet) object);
        {
            String lhsKontaktTelefonnummer;
            lhsKontaktTelefonnummer = this.getKontaktTelefonnummer();
            String rhsKontaktTelefonnummer;
            rhsKontaktTelefonnummer = that.getKontaktTelefonnummer();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "kontaktTelefonnummer", lhsKontaktTelefonnummer), LocatorUtils.property(thatLocator, "kontaktTelefonnummer", rhsKontaktTelefonnummer), lhsKontaktTelefonnummer, rhsKontaktTelefonnummer)) {
                return false;
            }
        }
        {
            NorskPostadresse lhsAdresse;
            lhsAdresse = this.getAdresse();
            NorskPostadresse rhsAdresse;
            rhsAdresse = that.getAdresse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "adresse", lhsAdresse), LocatorUtils.property(thatLocator, "adresse", rhsAdresse), lhsAdresse, rhsAdresse)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theKontaktTelefonnummer;
            theKontaktTelefonnummer = this.getKontaktTelefonnummer();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "kontaktTelefonnummer", theKontaktTelefonnummer), currentHashCode, theKontaktTelefonnummer);
        }
        {
            NorskPostadresse theAdresse;
            theAdresse = this.getAdresse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "adresse", theAdresse), currentHashCode, theAdresse);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theKontaktTelefonnummer;
            theKontaktTelefonnummer = this.getKontaktTelefonnummer();
            strategy.appendField(locator, this, "kontaktTelefonnummer", buffer, theKontaktTelefonnummer);
        }
        {
            NorskPostadresse theAdresse;
            theAdresse = this.getAdresse();
            strategy.appendField(locator, this, "adresse", buffer, theAdresse);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
        _other.kontaktTelefonnummer = this.kontaktTelefonnummer;
        _other.adresse = ((this.adresse == null)?null:this.adresse.newCopyBuilder(_other));
    }

    @Override
    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder);

    @Override
    public abstract Builder<Void> newCopyBuilder();

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
        final PropertyTree kontaktTelefonnummerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("kontaktTelefonnummer"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(kontaktTelefonnummerPropertyTree!= null):((kontaktTelefonnummerPropertyTree == null)||(!kontaktTelefonnummerPropertyTree.isLeaf())))) {
            _other.kontaktTelefonnummer = this.kontaktTelefonnummer;
        }
        final PropertyTree adressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresse"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adressePropertyTree!= null):((adressePropertyTree == null)||(!adressePropertyTree.isLeaf())))) {
            _other.adresse = ((this.adresse == null)?null:this.adresse.newCopyBuilder(_other, adressePropertyTree, _propertyTreeUse));
        }
    }

    @Override
    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    @Override
    public abstract Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    public static class Builder<_B >
        extends NavEnhet.Builder<_B>
        implements Buildable
    {

        private String kontaktTelefonnummer;
        private NorskPostadresse.Builder<Builder<_B>> adresse;

        public Builder(final _B _parentBuilder, final AdresseEnhet _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
                this.kontaktTelefonnummer = _other.kontaktTelefonnummer;
                this.adresse = ((_other.adresse == null)?null:_other.adresse.newCopyBuilder(this));
            }
        }

        public Builder(final _B _parentBuilder, final AdresseEnhet _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
                final PropertyTree kontaktTelefonnummerPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("kontaktTelefonnummer"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(kontaktTelefonnummerPropertyTree!= null):((kontaktTelefonnummerPropertyTree == null)||(!kontaktTelefonnummerPropertyTree.isLeaf())))) {
                    this.kontaktTelefonnummer = _other.kontaktTelefonnummer;
                }
                final PropertyTree adressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresse"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adressePropertyTree!= null):((adressePropertyTree == null)||(!adressePropertyTree.isLeaf())))) {
                    this.adresse = ((_other.adresse == null)?null:_other.adresse.newCopyBuilder(this, adressePropertyTree, _propertyTreeUse));
                }
            }
        }

        protected<_P extends AdresseEnhet >_P init(final _P _product) {
            _product.kontaktTelefonnummer = this.kontaktTelefonnummer;
            _product.adresse = ((this.adresse == null)?null:this.adresse.build());
            return super.init(_product);
        }

        /**
         * Sets the new value of "kontaktTelefonnummer" (any previous value will be replaced)
         * 
         * @param kontaktTelefonnummer
         *     New value of the "kontaktTelefonnummer" property.
         */
        public Builder<_B> withKontaktTelefonnummer(final String kontaktTelefonnummer) {
            this.kontaktTelefonnummer = kontaktTelefonnummer;
            return this;
        }

        /**
         * Sets the new value of "adresse" (any previous value will be replaced)
         * 
         * @param adresse
         *     New value of the "adresse" property.
         */
        public Builder<_B> withAdresse(final NorskPostadresse adresse) {
            this.adresse = ((adresse == null)?null:new NorskPostadresse.Builder<Builder<_B>>(this, adresse, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "adresse" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NorskPostadresse.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "adresse" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NorskPostadresse.Builder#end()} to return to the current builder.
         */
        public NorskPostadresse.Builder<? extends Builder<_B>> withAdresse() {
            return this.adresse = new NorskPostadresse.Builder<Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "enhetsId" (any previous value will be replaced)
         * 
         * @param enhetsId
         *     New value of the "enhetsId" property.
         */
        @Override
        public Builder<_B> withEnhetsId(final String enhetsId) {
            super.withEnhetsId(enhetsId);
            return this;
        }

        /**
         * Sets the new value of "enhetsNavn" (any previous value will be replaced)
         * 
         * @param enhetsNavn
         *     New value of the "enhetsNavn" property.
         */
        @Override
        public Builder<_B> withEnhetsNavn(final String enhetsNavn) {
            super.withEnhetsNavn(enhetsNavn);
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        @Override
        public Builder<_B> withBerik(final Boolean berik) {
            super.withBerik(berik);
            return this;
        }

        @Override
        public AdresseEnhet build() {
            return ((AdresseEnhet) _storedValue);
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends NavEnhet.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> kontaktTelefonnummer = null;
        private NorskPostadresse.Selector<TRoot, Selector<TRoot, TParent>> adresse = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.kontaktTelefonnummer!= null) {
                products.put("kontaktTelefonnummer", this.kontaktTelefonnummer.init());
            }
            if (this.adresse!= null) {
                products.put("adresse", this.adresse.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> kontaktTelefonnummer() {
            return ((this.kontaktTelefonnummer == null)?this.kontaktTelefonnummer = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "kontaktTelefonnummer"):this.kontaktTelefonnummer);
        }

        public NorskPostadresse.Selector<TRoot, Selector<TRoot, TParent>> adresse() {
            return ((this.adresse == null)?this.adresse = new NorskPostadresse.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "adresse"):this.adresse);
        }

    }

}
