//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import no.nav.dok.brevdata.felles.v1.simpletypes.AktoerType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Abstrakt type for sakspartType og mottakerType
 * 
 * <p>Java class for Aktoer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Aktoer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}Identifikator"/&gt;
 *         &lt;element name="typeKode" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}AktoerType"/&gt;
 *         &lt;element name="navn" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Aktoer", propOrder = {
    "id",
    "typeKode",
    "navn"
})
@XmlSeeAlso({
    Sakspart.class,
    Mottaker.class
})
public abstract class Aktoer implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected AktoerType typeKode;
    @XmlElement(required = true)
    protected String navn;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the typeKode property.
     * 
     * @return
     *     possible object is
     *     {@link AktoerType }
     *     
     */
    public AktoerType getTypeKode() {
        return typeKode;
    }

    /**
     * Sets the value of the typeKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AktoerType }
     *     
     */
    public void setTypeKode(AktoerType value) {
        this.typeKode = value;
    }

    /**
     * Gets the value of the navn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavn(String value) {
        this.navn = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Aktoer)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Aktoer that = ((Aktoer) object);
        {
            String lhsId;
            lhsId = this.getId();
            String rhsId;
            rhsId = that.getId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                return false;
            }
        }
        {
            AktoerType lhsTypeKode;
            lhsTypeKode = this.getTypeKode();
            AktoerType rhsTypeKode;
            rhsTypeKode = that.getTypeKode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "typeKode", lhsTypeKode), LocatorUtils.property(thatLocator, "typeKode", rhsTypeKode), lhsTypeKode, rhsTypeKode)) {
                return false;
            }
        }
        {
            String lhsNavn;
            lhsNavn = this.getNavn();
            String rhsNavn;
            rhsNavn = that.getNavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navn", lhsNavn), LocatorUtils.property(thatLocator, "navn", rhsNavn), lhsNavn, rhsNavn)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theId;
            theId = this.getId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
        }
        {
            AktoerType theTypeKode;
            theTypeKode = this.getTypeKode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "typeKode", theTypeKode), currentHashCode, theTypeKode);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navn", theNavn), currentHashCode, theNavn);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theId;
            theId = this.getId();
            strategy.appendField(locator, this, "id", buffer, theId);
        }
        {
            AktoerType theTypeKode;
            theTypeKode = this.getTypeKode();
            strategy.appendField(locator, this, "typeKode", buffer, theTypeKode);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            strategy.appendField(locator, this, "navn", buffer, theNavn);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        _other.id = this.id;
        _other.typeKode = this.typeKode;
        _other.navn = this.navn;
    }

    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder);

    public abstract Builder<Void> newCopyBuilder();

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree idPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("id"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(idPropertyTree!= null):((idPropertyTree == null)||(!idPropertyTree.isLeaf())))) {
            _other.id = this.id;
        }
        final PropertyTree typeKodePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("typeKode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(typeKodePropertyTree!= null):((typeKodePropertyTree == null)||(!typeKodePropertyTree.isLeaf())))) {
            _other.typeKode = this.typeKode;
        }
        final PropertyTree navnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navn"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navnPropertyTree!= null):((navnPropertyTree == null)||(!navnPropertyTree.isLeaf())))) {
            _other.navn = this.navn;
        }
    }

    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    public abstract Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final Aktoer _storedValue;
        private String id;
        private AktoerType typeKode;
        private String navn;

        public Builder(final _B _parentBuilder, final Aktoer _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.id = _other.id;
                    this.typeKode = _other.typeKode;
                    this.navn = _other.navn;
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final Aktoer _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree idPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("id"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(idPropertyTree!= null):((idPropertyTree == null)||(!idPropertyTree.isLeaf())))) {
                        this.id = _other.id;
                    }
                    final PropertyTree typeKodePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("typeKode"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(typeKodePropertyTree!= null):((typeKodePropertyTree == null)||(!typeKodePropertyTree.isLeaf())))) {
                        this.typeKode = _other.typeKode;
                    }
                    final PropertyTree navnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navn"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navnPropertyTree!= null):((navnPropertyTree == null)||(!navnPropertyTree.isLeaf())))) {
                        this.navn = _other.navn;
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends Aktoer >_P init(final _P _product) {
            _product.id = this.id;
            _product.typeKode = this.typeKode;
            _product.navn = this.navn;
            return _product;
        }

        /**
         * Sets the new value of "id" (any previous value will be replaced)
         * 
         * @param id
         *     New value of the "id" property.
         */
        public Builder<_B> withId(final String id) {
            this.id = id;
            return this;
        }

        /**
         * Sets the new value of "typeKode" (any previous value will be replaced)
         * 
         * @param typeKode
         *     New value of the "typeKode" property.
         */
        public Builder<_B> withTypeKode(final AktoerType typeKode) {
            this.typeKode = typeKode;
            return this;
        }

        /**
         * Sets the new value of "navn" (any previous value will be replaced)
         * 
         * @param navn
         *     New value of the "navn" property.
         */
        public Builder<_B> withNavn(final String navn) {
            this.navn = navn;
            return this;
        }

        @Override
        public Aktoer build() {
            return ((Aktoer) _storedValue);
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> id = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> typeKode = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> navn = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.id!= null) {
                products.put("id", this.id.init());
            }
            if (this.typeKode!= null) {
                products.put("typeKode", this.typeKode.init());
            }
            if (this.navn!= null) {
                products.put("navn", this.navn.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> id() {
            return ((this.id == null)?this.id = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "id"):this.id);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> typeKode() {
            return ((this.typeKode == null)?this.typeKode = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "typeKode"):this.typeKode);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> navn() {
            return ((this.navn == null)?this.navn = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "navn"):this.navn);
        }

    }

}
