//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import no.nav.dok.brevdata.felles.v1.simpletypes.AktoerType;
import no.nav.dok.brevdata.felles.v1.simpletypes.Spraakkode;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Gyldige mottakere er Person eller Organisasjon
 * 
 * <p>Java class for Mottaker complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mottaker"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Aktoer"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kortNavn" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *         &lt;element name="spraakkode" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}Spraakkode"/&gt;
 *         &lt;element name="mottakeradresse" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Adresse"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}berik"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mottaker", propOrder = {
    "kortNavn",
    "spraakkode",
    "mottakeradresse"
})
@XmlSeeAlso({
    Person.class,
    Organisasjon.class
})
public abstract class Mottaker
    extends Aktoer
    implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String kortNavn;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected Spraakkode spraakkode;
    @XmlElement(required = true)
    protected Adresse mottakeradresse;
    @XmlAttribute(name = "berik", namespace = "http://nav.no/dok/brevdata/felles/v1/NAVFelles")
    protected Boolean berik;

    /**
     * Gets the value of the kortNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKortNavn() {
        return kortNavn;
    }

    /**
     * Sets the value of the kortNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKortNavn(String value) {
        this.kortNavn = value;
    }

    /**
     * Gets the value of the spraakkode property.
     * 
     * @return
     *     possible object is
     *     {@link Spraakkode }
     *     
     */
    public Spraakkode getSpraakkode() {
        return spraakkode;
    }

    /**
     * Sets the value of the spraakkode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spraakkode }
     *     
     */
    public void setSpraakkode(Spraakkode value) {
        this.spraakkode = value;
    }

    /**
     * Gets the value of the mottakeradresse property.
     * 
     * @return
     *     possible object is
     *     {@link Adresse }
     *     
     */
    public Adresse getMottakeradresse() {
        return mottakeradresse;
    }

    /**
     * Sets the value of the mottakeradresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adresse }
     *     
     */
    public void setMottakeradresse(Adresse value) {
        this.mottakeradresse = value;
    }

    /**
     * Gets the value of the berik property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBerik() {
        if (berik == null) {
            return true;
        } else {
            return berik;
        }
    }

    /**
     * Sets the value of the berik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBerik(Boolean value) {
        this.berik = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Mottaker)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final Mottaker that = ((Mottaker) object);
        {
            String lhsKortNavn;
            lhsKortNavn = this.getKortNavn();
            String rhsKortNavn;
            rhsKortNavn = that.getKortNavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "kortNavn", lhsKortNavn), LocatorUtils.property(thatLocator, "kortNavn", rhsKortNavn), lhsKortNavn, rhsKortNavn)) {
                return false;
            }
        }
        {
            Spraakkode lhsSpraakkode;
            lhsSpraakkode = this.getSpraakkode();
            Spraakkode rhsSpraakkode;
            rhsSpraakkode = that.getSpraakkode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "spraakkode", lhsSpraakkode), LocatorUtils.property(thatLocator, "spraakkode", rhsSpraakkode), lhsSpraakkode, rhsSpraakkode)) {
                return false;
            }
        }
        {
            Adresse lhsMottakeradresse;
            lhsMottakeradresse = this.getMottakeradresse();
            Adresse rhsMottakeradresse;
            rhsMottakeradresse = that.getMottakeradresse();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "mottakeradresse", lhsMottakeradresse), LocatorUtils.property(thatLocator, "mottakeradresse", rhsMottakeradresse), lhsMottakeradresse, rhsMottakeradresse)) {
                return false;
            }
        }
        {
            boolean lhsBerik;
            lhsBerik = ((this.berik!= null)?this.isBerik():false);
            boolean rhsBerik;
            rhsBerik = ((that.berik!= null)?that.isBerik():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "berik", lhsBerik), LocatorUtils.property(thatLocator, "berik", rhsBerik), lhsBerik, rhsBerik)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theKortNavn;
            theKortNavn = this.getKortNavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "kortNavn", theKortNavn), currentHashCode, theKortNavn);
        }
        {
            Spraakkode theSpraakkode;
            theSpraakkode = this.getSpraakkode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "spraakkode", theSpraakkode), currentHashCode, theSpraakkode);
        }
        {
            Adresse theMottakeradresse;
            theMottakeradresse = this.getMottakeradresse();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "mottakeradresse", theMottakeradresse), currentHashCode, theMottakeradresse);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "berik", theBerik), currentHashCode, theBerik);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theKortNavn;
            theKortNavn = this.getKortNavn();
            strategy.appendField(locator, this, "kortNavn", buffer, theKortNavn);
        }
        {
            Spraakkode theSpraakkode;
            theSpraakkode = this.getSpraakkode();
            strategy.appendField(locator, this, "spraakkode", buffer, theSpraakkode);
        }
        {
            Adresse theMottakeradresse;
            theMottakeradresse = this.getMottakeradresse();
            strategy.appendField(locator, this, "mottakeradresse", buffer, theMottakeradresse);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            strategy.appendField(locator, this, "berik", buffer, theBerik);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
        _other.kortNavn = this.kortNavn;
        _other.spraakkode = this.spraakkode;
        _other.mottakeradresse = ((this.mottakeradresse == null)?null:this.mottakeradresse.newCopyBuilder(_other));
        _other.berik = this.berik;
    }

    @Override
    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder);

    @Override
    public abstract Builder<Void> newCopyBuilder();

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
        final PropertyTree kortNavnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("kortNavn"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(kortNavnPropertyTree!= null):((kortNavnPropertyTree == null)||(!kortNavnPropertyTree.isLeaf())))) {
            _other.kortNavn = this.kortNavn;
        }
        final PropertyTree spraakkodePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("spraakkode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(spraakkodePropertyTree!= null):((spraakkodePropertyTree == null)||(!spraakkodePropertyTree.isLeaf())))) {
            _other.spraakkode = this.spraakkode;
        }
        final PropertyTree mottakeradressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mottakeradresse"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(mottakeradressePropertyTree!= null):((mottakeradressePropertyTree == null)||(!mottakeradressePropertyTree.isLeaf())))) {
            _other.mottakeradresse = ((this.mottakeradresse == null)?null:this.mottakeradresse.newCopyBuilder(_other, mottakeradressePropertyTree, _propertyTreeUse));
        }
        final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
            _other.berik = this.berik;
        }
    }

    @Override
    public abstract<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    @Override
    public abstract Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse);

    public static class Builder<_B >
        extends Aktoer.Builder<_B>
        implements Buildable
    {

        private String kortNavn;
        private Spraakkode spraakkode;
        private Adresse.Builder<Builder<_B>> mottakeradresse;
        private Boolean berik;

        public Builder(final _B _parentBuilder, final Mottaker _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
                this.kortNavn = _other.kortNavn;
                this.spraakkode = _other.spraakkode;
                this.mottakeradresse = ((_other.mottakeradresse == null)?null:_other.mottakeradresse.newCopyBuilder(this));
                this.berik = _other.berik;
            }
        }

        public Builder(final _B _parentBuilder, final Mottaker _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
                final PropertyTree kortNavnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("kortNavn"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(kortNavnPropertyTree!= null):((kortNavnPropertyTree == null)||(!kortNavnPropertyTree.isLeaf())))) {
                    this.kortNavn = _other.kortNavn;
                }
                final PropertyTree spraakkodePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("spraakkode"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(spraakkodePropertyTree!= null):((spraakkodePropertyTree == null)||(!spraakkodePropertyTree.isLeaf())))) {
                    this.spraakkode = _other.spraakkode;
                }
                final PropertyTree mottakeradressePropertyTree = ((_propertyTree == null)?null:_propertyTree.get("mottakeradresse"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(mottakeradressePropertyTree!= null):((mottakeradressePropertyTree == null)||(!mottakeradressePropertyTree.isLeaf())))) {
                    this.mottakeradresse = ((_other.mottakeradresse == null)?null:_other.mottakeradresse.newCopyBuilder(this, mottakeradressePropertyTree, _propertyTreeUse));
                }
                final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
                    this.berik = _other.berik;
                }
            }
        }

        protected<_P extends Mottaker >_P init(final _P _product) {
            _product.kortNavn = this.kortNavn;
            _product.spraakkode = this.spraakkode;
            _product.mottakeradresse = ((this.mottakeradresse == null)?null:this.mottakeradresse.build());
            _product.berik = this.berik;
            return super.init(_product);
        }

        /**
         * Sets the new value of "kortNavn" (any previous value will be replaced)
         * 
         * @param kortNavn
         *     New value of the "kortNavn" property.
         */
        public Builder<_B> withKortNavn(final String kortNavn) {
            this.kortNavn = kortNavn;
            return this;
        }

        /**
         * Sets the new value of "spraakkode" (any previous value will be replaced)
         * 
         * @param spraakkode
         *     New value of the "spraakkode" property.
         */
        public Builder<_B> withSpraakkode(final Spraakkode spraakkode) {
            this.spraakkode = spraakkode;
            return this;
        }

        /**
         * Sets the new value of "mottakeradresse" (any previous value will be replaced)
         * 
         * @param mottakeradresse
         *     New value of the "mottakeradresse" property.
         */
        public Builder<_B> withMottakeradresse(final Adresse mottakeradresse) {
            this.mottakeradresse = ((mottakeradresse == null)?null:new Adresse.Builder<Builder<_B>>(this, mottakeradresse, false));
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        public Builder<_B> withBerik(final Boolean berik) {
            this.berik = berik;
            return this;
        }

        /**
         * Sets the new value of "id" (any previous value will be replaced)
         * 
         * @param id
         *     New value of the "id" property.
         */
        @Override
        public Builder<_B> withId(final String id) {
            super.withId(id);
            return this;
        }

        /**
         * Sets the new value of "typeKode" (any previous value will be replaced)
         * 
         * @param typeKode
         *     New value of the "typeKode" property.
         */
        @Override
        public Builder<_B> withTypeKode(final AktoerType typeKode) {
            super.withTypeKode(typeKode);
            return this;
        }

        /**
         * Sets the new value of "navn" (any previous value will be replaced)
         * 
         * @param navn
         *     New value of the "navn" property.
         */
        @Override
        public Builder<_B> withNavn(final String navn) {
            super.withNavn(navn);
            return this;
        }

        @Override
        public Mottaker build() {
            return ((Mottaker) _storedValue);
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends Aktoer.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> kortNavn = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> spraakkode = null;
        private Adresse.Selector<TRoot, Selector<TRoot, TParent>> mottakeradresse = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.kortNavn!= null) {
                products.put("kortNavn", this.kortNavn.init());
            }
            if (this.spraakkode!= null) {
                products.put("spraakkode", this.spraakkode.init());
            }
            if (this.mottakeradresse!= null) {
                products.put("mottakeradresse", this.mottakeradresse.init());
            }
            if (this.berik!= null) {
                products.put("berik", this.berik.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> kortNavn() {
            return ((this.kortNavn == null)?this.kortNavn = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "kortNavn"):this.kortNavn);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> spraakkode() {
            return ((this.spraakkode == null)?this.spraakkode = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "spraakkode"):this.spraakkode);
        }

        public Adresse.Selector<TRoot, Selector<TRoot, TParent>> mottakeradresse() {
            return ((this.mottakeradresse == null)?this.mottakeradresse = new Adresse.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "mottakeradresse"):this.mottakeradresse);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik() {
            return ((this.berik == null)?this.berik = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "berik"):this.berik);
        }

    }

}
