//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Navn på ansatt i NAV
 * 
 * <p>Java class for NavAnsatt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NavAnsatt"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="ansattId" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}Identifikator"/&gt;
 *         &lt;element name="navn" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute ref="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}berik"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavAnsatt", propOrder = {

})
public class NavAnsatt implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String ansattId;
    @XmlElement(required = true)
    protected String navn;
    @XmlAttribute(name = "berik", namespace = "http://nav.no/dok/brevdata/felles/v1/NAVFelles")
    protected Boolean berik;

    /**
     * Gets the value of the ansattId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsattId() {
        return ansattId;
    }

    /**
     * Sets the value of the ansattId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsattId(String value) {
        this.ansattId = value;
    }

    /**
     * Gets the value of the navn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavn(String value) {
        this.navn = value;
    }

    /**
     * Gets the value of the berik property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBerik() {
        if (berik == null) {
            return true;
        } else {
            return berik;
        }
    }

    /**
     * Sets the value of the berik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBerik(Boolean value) {
        this.berik = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof NavAnsatt)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final NavAnsatt that = ((NavAnsatt) object);
        {
            String lhsAnsattId;
            lhsAnsattId = this.getAnsattId();
            String rhsAnsattId;
            rhsAnsattId = that.getAnsattId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ansattId", lhsAnsattId), LocatorUtils.property(thatLocator, "ansattId", rhsAnsattId), lhsAnsattId, rhsAnsattId)) {
                return false;
            }
        }
        {
            String lhsNavn;
            lhsNavn = this.getNavn();
            String rhsNavn;
            rhsNavn = that.getNavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navn", lhsNavn), LocatorUtils.property(thatLocator, "navn", rhsNavn), lhsNavn, rhsNavn)) {
                return false;
            }
        }
        {
            boolean lhsBerik;
            lhsBerik = ((this.berik!= null)?this.isBerik():false);
            boolean rhsBerik;
            rhsBerik = ((that.berik!= null)?that.isBerik():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "berik", lhsBerik), LocatorUtils.property(thatLocator, "berik", rhsBerik), lhsBerik, rhsBerik)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theAnsattId;
            theAnsattId = this.getAnsattId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ansattId", theAnsattId), currentHashCode, theAnsattId);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navn", theNavn), currentHashCode, theNavn);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "berik", theBerik), currentHashCode, theBerik);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theAnsattId;
            theAnsattId = this.getAnsattId();
            strategy.appendField(locator, this, "ansattId", buffer, theAnsattId);
        }
        {
            String theNavn;
            theNavn = this.getNavn();
            strategy.appendField(locator, this, "navn", buffer, theNavn);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            strategy.appendField(locator, this, "berik", buffer, theBerik);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        _other.ansattId = this.ansattId;
        _other.navn = this.navn;
        _other.berik = this.berik;
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final NavAnsatt _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree ansattIdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ansattId"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ansattIdPropertyTree!= null):((ansattIdPropertyTree == null)||(!ansattIdPropertyTree.isLeaf())))) {
            _other.ansattId = this.ansattId;
        }
        final PropertyTree navnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navn"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navnPropertyTree!= null):((navnPropertyTree == null)||(!navnPropertyTree.isLeaf())))) {
            _other.navn = this.navn;
        }
        final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
            _other.berik = this.berik;
        }
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final NavAnsatt _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final NavAnsatt _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final NavAnsatt _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final NavAnsatt _storedValue;
        private String ansattId;
        private String navn;
        private Boolean berik;

        public Builder(final _B _parentBuilder, final NavAnsatt _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.ansattId = _other.ansattId;
                    this.navn = _other.navn;
                    this.berik = _other.berik;
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final NavAnsatt _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree ansattIdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("ansattId"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(ansattIdPropertyTree!= null):((ansattIdPropertyTree == null)||(!ansattIdPropertyTree.isLeaf())))) {
                        this.ansattId = _other.ansattId;
                    }
                    final PropertyTree navnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navn"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navnPropertyTree!= null):((navnPropertyTree == null)||(!navnPropertyTree.isLeaf())))) {
                        this.navn = _other.navn;
                    }
                    final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
                        this.berik = _other.berik;
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends NavAnsatt >_P init(final _P _product) {
            _product.ansattId = this.ansattId;
            _product.navn = this.navn;
            _product.berik = this.berik;
            return _product;
        }

        /**
         * Sets the new value of "ansattId" (any previous value will be replaced)
         * 
         * @param ansattId
         *     New value of the "ansattId" property.
         */
        public Builder<_B> withAnsattId(final String ansattId) {
            this.ansattId = ansattId;
            return this;
        }

        /**
         * Sets the new value of "navn" (any previous value will be replaced)
         * 
         * @param navn
         *     New value of the "navn" property.
         */
        public Builder<_B> withNavn(final String navn) {
            this.navn = navn;
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        public Builder<_B> withBerik(final Boolean berik) {
            this.berik = berik;
            return this;
        }

        @Override
        public NavAnsatt build() {
            if (_storedValue == null) {
                return this.init(new NavAnsatt());
            } else {
                return ((NavAnsatt) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> ansattId = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> navn = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.ansattId!= null) {
                products.put("ansattId", this.ansattId.init());
            }
            if (this.navn!= null) {
                products.put("navn", this.navn.init());
            }
            if (this.berik!= null) {
                products.put("berik", this.berik.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> ansattId() {
            return ((this.ansattId == null)?this.ansattId = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "ansattId"):this.ansattId);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> navn() {
            return ((this.navn == null)?this.navn = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "navn"):this.navn);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik() {
            return ((this.berik == null)?this.berik = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "berik"):this.berik);
        }

    }

}
