//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Navn på enhet i NAV
 * 
 * <p>Java class for NavEnhet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NavEnhet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enhetsId" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}Identifikator"/&gt;
 *         &lt;element name="enhetsNavn" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}berik"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavEnhet", propOrder = {
    "enhetsId",
    "enhetsNavn"
})
@XmlSeeAlso({
    AdresseEnhet.class
})
public class NavEnhet implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String enhetsId;
    @XmlElement(required = true)
    protected String enhetsNavn;
    @XmlAttribute(name = "berik", namespace = "http://nav.no/dok/brevdata/felles/v1/NAVFelles")
    protected Boolean berik;

    /**
     * Gets the value of the enhetsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhetsId() {
        return enhetsId;
    }

    /**
     * Sets the value of the enhetsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhetsId(String value) {
        this.enhetsId = value;
    }

    /**
     * Gets the value of the enhetsNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhetsNavn() {
        return enhetsNavn;
    }

    /**
     * Sets the value of the enhetsNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhetsNavn(String value) {
        this.enhetsNavn = value;
    }

    /**
     * Gets the value of the berik property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBerik() {
        if (berik == null) {
            return true;
        } else {
            return berik;
        }
    }

    /**
     * Sets the value of the berik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBerik(Boolean value) {
        this.berik = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof NavEnhet)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final NavEnhet that = ((NavEnhet) object);
        {
            String lhsEnhetsId;
            lhsEnhetsId = this.getEnhetsId();
            String rhsEnhetsId;
            rhsEnhetsId = that.getEnhetsId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "enhetsId", lhsEnhetsId), LocatorUtils.property(thatLocator, "enhetsId", rhsEnhetsId), lhsEnhetsId, rhsEnhetsId)) {
                return false;
            }
        }
        {
            String lhsEnhetsNavn;
            lhsEnhetsNavn = this.getEnhetsNavn();
            String rhsEnhetsNavn;
            rhsEnhetsNavn = that.getEnhetsNavn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "enhetsNavn", lhsEnhetsNavn), LocatorUtils.property(thatLocator, "enhetsNavn", rhsEnhetsNavn), lhsEnhetsNavn, rhsEnhetsNavn)) {
                return false;
            }
        }
        {
            boolean lhsBerik;
            lhsBerik = ((this.berik!= null)?this.isBerik():false);
            boolean rhsBerik;
            rhsBerik = ((that.berik!= null)?that.isBerik():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "berik", lhsBerik), LocatorUtils.property(thatLocator, "berik", rhsBerik), lhsBerik, rhsBerik)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theEnhetsId;
            theEnhetsId = this.getEnhetsId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "enhetsId", theEnhetsId), currentHashCode, theEnhetsId);
        }
        {
            String theEnhetsNavn;
            theEnhetsNavn = this.getEnhetsNavn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "enhetsNavn", theEnhetsNavn), currentHashCode, theEnhetsNavn);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "berik", theBerik), currentHashCode, theBerik);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theEnhetsId;
            theEnhetsId = this.getEnhetsId();
            strategy.appendField(locator, this, "enhetsId", buffer, theEnhetsId);
        }
        {
            String theEnhetsNavn;
            theEnhetsNavn = this.getEnhetsNavn();
            strategy.appendField(locator, this, "enhetsNavn", buffer, theEnhetsNavn);
        }
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            strategy.appendField(locator, this, "berik", buffer, theBerik);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        _other.enhetsId = this.enhetsId;
        _other.enhetsNavn = this.enhetsNavn;
        _other.berik = this.berik;
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final NavEnhet _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree enhetsIdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("enhetsId"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(enhetsIdPropertyTree!= null):((enhetsIdPropertyTree == null)||(!enhetsIdPropertyTree.isLeaf())))) {
            _other.enhetsId = this.enhetsId;
        }
        final PropertyTree enhetsNavnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("enhetsNavn"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(enhetsNavnPropertyTree!= null):((enhetsNavnPropertyTree == null)||(!enhetsNavnPropertyTree.isLeaf())))) {
            _other.enhetsNavn = this.enhetsNavn;
        }
        final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
            _other.berik = this.berik;
        }
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final NavEnhet _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final NavEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final NavEnhet _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final NavEnhet _storedValue;
        private String enhetsId;
        private String enhetsNavn;
        private Boolean berik;

        public Builder(final _B _parentBuilder, final NavEnhet _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.enhetsId = _other.enhetsId;
                    this.enhetsNavn = _other.enhetsNavn;
                    this.berik = _other.berik;
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final NavEnhet _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree enhetsIdPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("enhetsId"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(enhetsIdPropertyTree!= null):((enhetsIdPropertyTree == null)||(!enhetsIdPropertyTree.isLeaf())))) {
                        this.enhetsId = _other.enhetsId;
                    }
                    final PropertyTree enhetsNavnPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("enhetsNavn"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(enhetsNavnPropertyTree!= null):((enhetsNavnPropertyTree == null)||(!enhetsNavnPropertyTree.isLeaf())))) {
                        this.enhetsNavn = _other.enhetsNavn;
                    }
                    final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
                        this.berik = _other.berik;
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends NavEnhet >_P init(final _P _product) {
            _product.enhetsId = this.enhetsId;
            _product.enhetsNavn = this.enhetsNavn;
            _product.berik = this.berik;
            return _product;
        }

        /**
         * Sets the new value of "enhetsId" (any previous value will be replaced)
         * 
         * @param enhetsId
         *     New value of the "enhetsId" property.
         */
        public Builder<_B> withEnhetsId(final String enhetsId) {
            this.enhetsId = enhetsId;
            return this;
        }

        /**
         * Sets the new value of "enhetsNavn" (any previous value will be replaced)
         * 
         * @param enhetsNavn
         *     New value of the "enhetsNavn" property.
         */
        public Builder<_B> withEnhetsNavn(final String enhetsNavn) {
            this.enhetsNavn = enhetsNavn;
            return this;
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        public Builder<_B> withBerik(final Boolean berik) {
            this.berik = berik;
            return this;
        }

        @Override
        public NavEnhet build() {
            if (_storedValue == null) {
                return this.init(new NavEnhet());
            } else {
                return ((NavEnhet) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> enhetsId = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> enhetsNavn = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.enhetsId!= null) {
                products.put("enhetsId", this.enhetsId.init());
            }
            if (this.enhetsNavn!= null) {
                products.put("enhetsNavn", this.enhetsNavn.init());
            }
            if (this.berik!= null) {
                products.put("berik", this.berik.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> enhetsId() {
            return ((this.enhetsId == null)?this.enhetsId = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "enhetsId"):this.enhetsId);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> enhetsNavn() {
            return ((this.enhetsNavn == null)?this.enhetsNavn = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "enhetsNavn"):this.enhetsNavn);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik() {
            return ((this.berik == null)?this.berik = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "berik"):this.berik);
        }

    }

}
