//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.dok.brevdata.felles.v1.navfelles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.dok.brevdata.felles.v1.navfelles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sakspart }
     * 
     */
    public Sakspart createSakspart() {
        return new Sakspart();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Organisasjon }
     * 
     */
    public Organisasjon createOrganisasjon() {
        return new Organisasjon();
    }

    /**
     * Create an instance of {@link NorskPostadresse }
     * 
     */
    public NorskPostadresse createNorskPostadresse() {
        return new NorskPostadresse();
    }

    /**
     * Create an instance of {@link UtenlandskPostadresse }
     * 
     */
    public UtenlandskPostadresse createUtenlandskPostadresse() {
        return new UtenlandskPostadresse();
    }

    /**
     * Create an instance of {@link Saksbehandler }
     * 
     */
    public Saksbehandler createSaksbehandler() {
        return new Saksbehandler();
    }

    /**
     * Create an instance of {@link NavAnsatt }
     * 
     */
    public NavAnsatt createNavAnsatt() {
        return new NavAnsatt();
    }

    /**
     * Create an instance of {@link NavEnhet }
     * 
     */
    public NavEnhet createNavEnhet() {
        return new NavEnhet();
    }

    /**
     * Create an instance of {@link Kontaktinformasjon }
     * 
     */
    public Kontaktinformasjon createKontaktinformasjon() {
        return new Kontaktinformasjon();
    }

    /**
     * Create an instance of {@link Returadresse }
     * 
     */
    public Returadresse createReturadresse() {
        return new Returadresse();
    }

    /**
     * Create an instance of {@link Postadresse }
     * 
     */
    public Postadresse createPostadresse() {
        return new Postadresse();
    }

    /**
     * Create an instance of {@link Besoksadresse }
     * 
     */
    public Besoksadresse createBesoksadresse() {
        return new Besoksadresse();
    }

}
