//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import no.nav.dok.brevdata.felles.v1.simpletypes.AktoerType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Sakspart viser til personen vedtaket gjelder
 * 
 * <p>Java class for Sakspart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sakspart"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Aktoer"&gt;
 *       &lt;attribute ref="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}berik"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sakspart")
public class Sakspart
    extends Aktoer
    implements Equals, HashCode, ToString
{

    @XmlAttribute(name = "berik", namespace = "http://nav.no/dok/brevdata/felles/v1/NAVFelles")
    protected Boolean berik;

    /**
     * Gets the value of the berik property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBerik() {
        if (berik == null) {
            return true;
        } else {
            return berik;
        }
    }

    /**
     * Sets the value of the berik property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBerik(Boolean value) {
        this.berik = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Sakspart)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final Sakspart that = ((Sakspart) object);
        {
            boolean lhsBerik;
            lhsBerik = ((this.berik!= null)?this.isBerik():false);
            boolean rhsBerik;
            rhsBerik = ((that.berik!= null)?that.isBerik():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "berik", lhsBerik), LocatorUtils.property(thatLocator, "berik", rhsBerik), lhsBerik, rhsBerik)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "berik", theBerik), currentHashCode, theBerik);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            boolean theBerik;
            theBerik = ((this.berik!= null)?this.isBerik():false);
            strategy.appendField(locator, this, "berik", buffer, theBerik);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
        _other.berik = this.berik;
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    @Override
    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final Aktoer _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Sakspart _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
        final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
            _other.berik = this.berik;
        }
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    @Override
    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final Aktoer _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final Sakspart _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final Aktoer _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final Sakspart _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final Aktoer _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final Sakspart _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >
        extends Aktoer.Builder<_B>
        implements Buildable
    {

        private Boolean berik;

        public Builder(final _B _parentBuilder, final Sakspart _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
                this.berik = _other.berik;
            }
        }

        public Builder(final _B _parentBuilder, final Sakspart _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
                final PropertyTree berikPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("berik"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(berikPropertyTree!= null):((berikPropertyTree == null)||(!berikPropertyTree.isLeaf())))) {
                    this.berik = _other.berik;
                }
            }
        }

        protected<_P extends Sakspart >_P init(final _P _product) {
            _product.berik = this.berik;
            return super.init(_product);
        }

        /**
         * Sets the new value of "berik" (any previous value will be replaced)
         * 
         * @param berik
         *     New value of the "berik" property.
         */
        public Builder<_B> withBerik(final Boolean berik) {
            this.berik = berik;
            return this;
        }

        /**
         * Sets the new value of "id" (any previous value will be replaced)
         * 
         * @param id
         *     New value of the "id" property.
         */
        @Override
        public Builder<_B> withId(final String id) {
            super.withId(id);
            return this;
        }

        /**
         * Sets the new value of "typeKode" (any previous value will be replaced)
         * 
         * @param typeKode
         *     New value of the "typeKode" property.
         */
        @Override
        public Builder<_B> withTypeKode(final AktoerType typeKode) {
            super.withTypeKode(typeKode);
            return this;
        }

        /**
         * Sets the new value of "navn" (any previous value will be replaced)
         * 
         * @param navn
         *     New value of the "navn" property.
         */
        @Override
        public Builder<_B> withNavn(final String navn) {
            super.withNavn(navn);
            return this;
        }

        @Override
        public Sakspart build() {
            if (_storedValue == null) {
                return this.init(new Sakspart());
            } else {
                return ((Sakspart) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends Aktoer.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.berik!= null) {
                products.put("berik", this.berik.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> berik() {
            return ((this.berik == null)?this.berik = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "berik"):this.berik);
        }

    }

}
