//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * <p>Java class for Saksbehandler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Saksbehandler"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="navAnsatt" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}NavAnsatt"/&gt;
 *         &lt;element name="navEnhet" type="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}NavEnhet"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Saksbehandler", propOrder = {

})
public class Saksbehandler implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected NavAnsatt navAnsatt;
    @XmlElement(required = true)
    protected NavEnhet navEnhet;

    /**
     * Gets the value of the navAnsatt property.
     * 
     * @return
     *     possible object is
     *     {@link NavAnsatt }
     *     
     */
    public NavAnsatt getNavAnsatt() {
        return navAnsatt;
    }

    /**
     * Sets the value of the navAnsatt property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavAnsatt }
     *     
     */
    public void setNavAnsatt(NavAnsatt value) {
        this.navAnsatt = value;
    }

    /**
     * Gets the value of the navEnhet property.
     * 
     * @return
     *     possible object is
     *     {@link NavEnhet }
     *     
     */
    public NavEnhet getNavEnhet() {
        return navEnhet;
    }

    /**
     * Sets the value of the navEnhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavEnhet }
     *     
     */
    public void setNavEnhet(NavEnhet value) {
        this.navEnhet = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Saksbehandler)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Saksbehandler that = ((Saksbehandler) object);
        {
            NavAnsatt lhsNavAnsatt;
            lhsNavAnsatt = this.getNavAnsatt();
            NavAnsatt rhsNavAnsatt;
            rhsNavAnsatt = that.getNavAnsatt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navAnsatt", lhsNavAnsatt), LocatorUtils.property(thatLocator, "navAnsatt", rhsNavAnsatt), lhsNavAnsatt, rhsNavAnsatt)) {
                return false;
            }
        }
        {
            NavEnhet lhsNavEnhet;
            lhsNavEnhet = this.getNavEnhet();
            NavEnhet rhsNavEnhet;
            rhsNavEnhet = that.getNavEnhet();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "navEnhet", lhsNavEnhet), LocatorUtils.property(thatLocator, "navEnhet", rhsNavEnhet), lhsNavEnhet, rhsNavEnhet)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            NavAnsatt theNavAnsatt;
            theNavAnsatt = this.getNavAnsatt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navAnsatt", theNavAnsatt), currentHashCode, theNavAnsatt);
        }
        {
            NavEnhet theNavEnhet;
            theNavEnhet = this.getNavEnhet();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "navEnhet", theNavEnhet), currentHashCode, theNavEnhet);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            NavAnsatt theNavAnsatt;
            theNavAnsatt = this.getNavAnsatt();
            strategy.appendField(locator, this, "navAnsatt", buffer, theNavAnsatt);
        }
        {
            NavEnhet theNavEnhet;
            theNavEnhet = this.getNavEnhet();
            strategy.appendField(locator, this, "navEnhet", buffer, theNavEnhet);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        _other.navAnsatt = ((this.navAnsatt == null)?null:this.navAnsatt.newCopyBuilder(_other));
        _other.navEnhet = ((this.navEnhet == null)?null:this.navEnhet.newCopyBuilder(_other));
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final Saksbehandler _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree navAnsattPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navAnsatt"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navAnsattPropertyTree!= null):((navAnsattPropertyTree == null)||(!navAnsattPropertyTree.isLeaf())))) {
            _other.navAnsatt = ((this.navAnsatt == null)?null:this.navAnsatt.newCopyBuilder(_other, navAnsattPropertyTree, _propertyTreeUse));
        }
        final PropertyTree navEnhetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navEnhet"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navEnhetPropertyTree!= null):((navEnhetPropertyTree == null)||(!navEnhetPropertyTree.isLeaf())))) {
            _other.navEnhet = ((this.navEnhet == null)?null:this.navEnhet.newCopyBuilder(_other, navEnhetPropertyTree, _propertyTreeUse));
        }
    }

    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final Saksbehandler _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final Saksbehandler _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final Saksbehandler _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >implements Buildable
    {

        protected final _B _parentBuilder;
        protected final Saksbehandler _storedValue;
        private NavAnsatt.Builder<Builder<_B>> navAnsatt;
        private NavEnhet.Builder<Builder<_B>> navEnhet;

        public Builder(final _B _parentBuilder, final Saksbehandler _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    this.navAnsatt = ((_other.navAnsatt == null)?null:_other.navAnsatt.newCopyBuilder(this));
                    this.navEnhet = ((_other.navEnhet == null)?null:_other.navEnhet.newCopyBuilder(this));
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final Saksbehandler _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other!= null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree navAnsattPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navAnsatt"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navAnsattPropertyTree!= null):((navAnsattPropertyTree == null)||(!navAnsattPropertyTree.isLeaf())))) {
                        this.navAnsatt = ((_other.navAnsatt == null)?null:_other.navAnsatt.newCopyBuilder(this, navAnsattPropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree navEnhetPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("navEnhet"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(navEnhetPropertyTree!= null):((navEnhetPropertyTree == null)||(!navEnhetPropertyTree.isLeaf())))) {
                        this.navEnhet = ((_other.navEnhet == null)?null:_other.navEnhet.newCopyBuilder(this, navEnhetPropertyTree, _propertyTreeUse));
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected<_P extends Saksbehandler >_P init(final _P _product) {
            _product.navAnsatt = ((this.navAnsatt == null)?null:this.navAnsatt.build());
            _product.navEnhet = ((this.navEnhet == null)?null:this.navEnhet.build());
            return _product;
        }

        /**
         * Sets the new value of "navAnsatt" (any previous value will be replaced)
         * 
         * @param navAnsatt
         *     New value of the "navAnsatt" property.
         */
        public Builder<_B> withNavAnsatt(final NavAnsatt navAnsatt) {
            this.navAnsatt = ((navAnsatt == null)?null:new NavAnsatt.Builder<Builder<_B>>(this, navAnsatt, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "navAnsatt" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NavAnsatt.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "navAnsatt" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NavAnsatt.Builder#end()} to return to the current builder.
         */
        public NavAnsatt.Builder<? extends Builder<_B>> withNavAnsatt() {
            return this.navAnsatt = new NavAnsatt.Builder<Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "navEnhet" (any previous value will be replaced)
         * 
         * @param navEnhet
         *     New value of the "navEnhet" property.
         */
        public Builder<_B> withNavEnhet(final NavEnhet navEnhet) {
            this.navEnhet = ((navEnhet == null)?null:new NavEnhet.Builder<Builder<_B>>(this, navEnhet, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "navEnhet" property (replacing previous value).
         * Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NavEnhet.Builder#end()} to return to the current builder.
         * 
         * @return
         *     A new builder to build the value of the "navEnhet" property.
         *     Use {@link no.nav.dok.brevdata.felles.v1.navfelles.NavEnhet.Builder#end()} to return to the current builder.
         */
        public NavEnhet.Builder<? extends Builder<_B>> withNavEnhet() {
            return this.navEnhet = new NavEnhet.Builder<Builder<_B>>(this, null, false);
        }

        @Override
        public Saksbehandler build() {
            if (_storedValue == null) {
                return this.init(new Saksbehandler());
            } else {
                return ((Saksbehandler) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends com.kscs.util.jaxb.Selector<TRoot, TParent>
    {

        private NavAnsatt.Selector<TRoot, Selector<TRoot, TParent>> navAnsatt = null;
        private NavEnhet.Selector<TRoot, Selector<TRoot, TParent>> navEnhet = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.navAnsatt!= null) {
                products.put("navAnsatt", this.navAnsatt.init());
            }
            if (this.navEnhet!= null) {
                products.put("navEnhet", this.navEnhet.init());
            }
            return products;
        }

        public NavAnsatt.Selector<TRoot, Selector<TRoot, TParent>> navAnsatt() {
            return ((this.navAnsatt == null)?this.navAnsatt = new NavAnsatt.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "navAnsatt"):this.navAnsatt);
        }

        public NavEnhet.Selector<TRoot, Selector<TRoot, TParent>> navEnhet() {
            return ((this.navEnhet == null)?this.navEnhet = new NavEnhet.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "navEnhet"):this.navEnhet);
        }

    }

}
