//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.navfelles;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.HashMap;
import java.util.Map;


/**
 * Gyldig adressefelt som representerer en utenlandsk adresse
 * 
 * <p>Java class for UtenlandskPostadresse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UtenlandskPostadresse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://nav.no/dok/brevdata/felles/v1/NAVFelles}Adresse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="adresselinje1" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *         &lt;element name="adresselinje2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="adresselinje3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="land" type="{http://nav.no/dok/brevdata/felles/v1/SimpleTypes}NonEmptyString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UtenlandskPostadresse", propOrder = {
    "adresselinje1",
    "adresselinje2",
    "adresselinje3",
    "land"
})
public class UtenlandskPostadresse
    extends Adresse
    implements Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected String adresselinje1;
    protected String adresselinje2;
    protected String adresselinje3;
    @XmlElement(required = true)
    protected String land;

    /**
     * Gets the value of the adresselinje1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresselinje1() {
        return adresselinje1;
    }

    /**
     * Sets the value of the adresselinje1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresselinje1(String value) {
        this.adresselinje1 = value;
    }

    /**
     * Gets the value of the adresselinje2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresselinje2() {
        return adresselinje2;
    }

    /**
     * Sets the value of the adresselinje2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresselinje2(String value) {
        this.adresselinje2 = value;
    }

    /**
     * Gets the value of the adresselinje3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresselinje3() {
        return adresselinje3;
    }

    /**
     * Sets the value of the adresselinje3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresselinje3(String value) {
        this.adresselinje3 = value;
    }

    /**
     * Gets the value of the land property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLand() {
        return land;
    }

    /**
     * Sets the value of the land property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLand(String value) {
        this.land = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof UtenlandskPostadresse)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final UtenlandskPostadresse that = ((UtenlandskPostadresse) object);
        {
            String lhsAdresselinje1;
            lhsAdresselinje1 = this.getAdresselinje1();
            String rhsAdresselinje1;
            rhsAdresselinje1 = that.getAdresselinje1();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "adresselinje1", lhsAdresselinje1), LocatorUtils.property(thatLocator, "adresselinje1", rhsAdresselinje1), lhsAdresselinje1, rhsAdresselinje1)) {
                return false;
            }
        }
        {
            String lhsAdresselinje2;
            lhsAdresselinje2 = this.getAdresselinje2();
            String rhsAdresselinje2;
            rhsAdresselinje2 = that.getAdresselinje2();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "adresselinje2", lhsAdresselinje2), LocatorUtils.property(thatLocator, "adresselinje2", rhsAdresselinje2), lhsAdresselinje2, rhsAdresselinje2)) {
                return false;
            }
        }
        {
            String lhsAdresselinje3;
            lhsAdresselinje3 = this.getAdresselinje3();
            String rhsAdresselinje3;
            rhsAdresselinje3 = that.getAdresselinje3();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "adresselinje3", lhsAdresselinje3), LocatorUtils.property(thatLocator, "adresselinje3", rhsAdresselinje3), lhsAdresselinje3, rhsAdresselinje3)) {
                return false;
            }
        }
        {
            String lhsLand;
            lhsLand = this.getLand();
            String rhsLand;
            rhsLand = that.getLand();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "land", lhsLand), LocatorUtils.property(thatLocator, "land", rhsLand), lhsLand, rhsLand)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theAdresselinje1;
            theAdresselinje1 = this.getAdresselinje1();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "adresselinje1", theAdresselinje1), currentHashCode, theAdresselinje1);
        }
        {
            String theAdresselinje2;
            theAdresselinje2 = this.getAdresselinje2();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "adresselinje2", theAdresselinje2), currentHashCode, theAdresselinje2);
        }
        {
            String theAdresselinje3;
            theAdresselinje3 = this.getAdresselinje3();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "adresselinje3", theAdresselinje3), currentHashCode, theAdresselinje3);
        }
        {
            String theLand;
            theLand = this.getLand();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "land", theLand), currentHashCode, theLand);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theAdresselinje1;
            theAdresselinje1 = this.getAdresselinje1();
            strategy.appendField(locator, this, "adresselinje1", buffer, theAdresselinje1);
        }
        {
            String theAdresselinje2;
            theAdresselinje2 = this.getAdresselinje2();
            strategy.appendField(locator, this, "adresselinje2", buffer, theAdresselinje2);
        }
        {
            String theAdresselinje3;
            theAdresselinje3 = this.getAdresselinje3();
            strategy.appendField(locator, this, "adresselinje3", buffer, theAdresselinje3);
        }
        {
            String theLand;
            theLand = this.getLand();
            strategy.appendField(locator, this, "land", buffer, theLand);
        }
        return buffer;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other) {
        super.copyTo(_other);
        _other.adresselinje1 = this.adresselinje1;
        _other.adresselinje2 = this.adresselinje2;
        _other.adresselinje3 = this.adresselinje3;
        _other.land = this.land;
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new Builder<_B>(_parentBuilder, this, true);
    }

    @Override
    public Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static Builder<Void> builder() {
        return new Builder<Void>(null, null, false);
    }

    public static<_B > Builder<_B> copyOf(final Adresse _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final UtenlandskPostadresse _other) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     * 
     * @param _other
     *     A builder instance to which the state of this object will be copied.
     */
    public<_B >void copyTo(final Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        super.copyTo(_other, _propertyTree, _propertyTreeUse);
        final PropertyTree adresselinje1PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje1"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje1PropertyTree!= null):((adresselinje1PropertyTree == null)||(!adresselinje1PropertyTree.isLeaf())))) {
            _other.adresselinje1 = this.adresselinje1;
        }
        final PropertyTree adresselinje2PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje2"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje2PropertyTree!= null):((adresselinje2PropertyTree == null)||(!adresselinje2PropertyTree.isLeaf())))) {
            _other.adresselinje2 = this.adresselinje2;
        }
        final PropertyTree adresselinje3PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje3"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje3PropertyTree!= null):((adresselinje3PropertyTree == null)||(!adresselinje3PropertyTree.isLeaf())))) {
            _other.adresselinje3 = this.adresselinje3;
        }
        final PropertyTree landPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("land"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(landPropertyTree!= null):((landPropertyTree == null)||(!landPropertyTree.isLeaf())))) {
            _other.land = this.land;
        }
    }

    @Override
    public<_B > Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    @Override
    public Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static<_B > Builder<_B> copyOf(final Adresse _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static<_B > Builder<_B> copyOf(final UtenlandskPostadresse _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final Builder<_B> _newBuilder = new Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static Builder<Void> copyExcept(final Adresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyExcept(final UtenlandskPostadresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static Builder<Void> copyOnly(final Adresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static Builder<Void> copyOnly(final UtenlandskPostadresse _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B >
        extends Adresse.Builder<_B>
        implements Buildable
    {

        private String adresselinje1;
        private String adresselinje2;
        private String adresselinje3;
        private String land;

        public Builder(final _B _parentBuilder, final UtenlandskPostadresse _other, final boolean _copy) {
            super(_parentBuilder, _other, _copy);
            if (_other!= null) {
                this.adresselinje1 = _other.adresselinje1;
                this.adresselinje2 = _other.adresselinje2;
                this.adresselinje3 = _other.adresselinje3;
                this.land = _other.land;
            }
        }

        public Builder(final _B _parentBuilder, final UtenlandskPostadresse _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            super(_parentBuilder, _other, _copy, _propertyTree, _propertyTreeUse);
            if (_other!= null) {
                final PropertyTree adresselinje1PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje1"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje1PropertyTree!= null):((adresselinje1PropertyTree == null)||(!adresselinje1PropertyTree.isLeaf())))) {
                    this.adresselinje1 = _other.adresselinje1;
                }
                final PropertyTree adresselinje2PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje2"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje2PropertyTree!= null):((adresselinje2PropertyTree == null)||(!adresselinje2PropertyTree.isLeaf())))) {
                    this.adresselinje2 = _other.adresselinje2;
                }
                final PropertyTree adresselinje3PropertyTree = ((_propertyTree == null)?null:_propertyTree.get("adresselinje3"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(adresselinje3PropertyTree!= null):((adresselinje3PropertyTree == null)||(!adresselinje3PropertyTree.isLeaf())))) {
                    this.adresselinje3 = _other.adresselinje3;
                }
                final PropertyTree landPropertyTree = ((_propertyTree == null)?null:_propertyTree.get("land"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE)?(landPropertyTree!= null):((landPropertyTree == null)||(!landPropertyTree.isLeaf())))) {
                    this.land = _other.land;
                }
            }
        }

        protected<_P extends UtenlandskPostadresse >_P init(final _P _product) {
            _product.adresselinje1 = this.adresselinje1;
            _product.adresselinje2 = this.adresselinje2;
            _product.adresselinje3 = this.adresselinje3;
            _product.land = this.land;
            return super.init(_product);
        }

        /**
         * Sets the new value of "adresselinje1" (any previous value will be replaced)
         * 
         * @param adresselinje1
         *     New value of the "adresselinje1" property.
         */
        public Builder<_B> withAdresselinje1(final String adresselinje1) {
            this.adresselinje1 = adresselinje1;
            return this;
        }

        /**
         * Sets the new value of "adresselinje2" (any previous value will be replaced)
         * 
         * @param adresselinje2
         *     New value of the "adresselinje2" property.
         */
        public Builder<_B> withAdresselinje2(final String adresselinje2) {
            this.adresselinje2 = adresselinje2;
            return this;
        }

        /**
         * Sets the new value of "adresselinje3" (any previous value will be replaced)
         * 
         * @param adresselinje3
         *     New value of the "adresselinje3" property.
         */
        public Builder<_B> withAdresselinje3(final String adresselinje3) {
            this.adresselinje3 = adresselinje3;
            return this;
        }

        /**
         * Sets the new value of "land" (any previous value will be replaced)
         * 
         * @param land
         *     New value of the "land" property.
         */
        public Builder<_B> withLand(final String land) {
            this.land = land;
            return this;
        }

        @Override
        public UtenlandskPostadresse build() {
            if (_storedValue == null) {
                return this.init(new UtenlandskPostadresse());
            } else {
                return ((UtenlandskPostadresse) _storedValue);
            }
        }

    }

    public static class Select
        extends Selector<Select, Void>
    {


        Select() {
            super(null, null, null);
        }

        public static Select _root() {
            return new Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?> , TParent >
        extends Adresse.Selector<TRoot, TParent>
    {

        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje1 = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje2 = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje3 = null;
        private com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> land = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.adresselinje1 != null) {
                products.put("adresselinje1", this.adresselinje1 .init());
            }
            if (this.adresselinje2 != null) {
                products.put("adresselinje2", this.adresselinje2 .init());
            }
            if (this.adresselinje3 != null) {
                products.put("adresselinje3", this.adresselinje3 .init());
            }
            if (this.land!= null) {
                products.put("land", this.land.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje1() {
            return ((this.adresselinje1 == null)?this.adresselinje1 = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "adresselinje1"):this.adresselinje1);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje2() {
            return ((this.adresselinje2 == null)?this.adresselinje2 = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "adresselinje2"):this.adresselinje2);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> adresselinje3() {
            return ((this.adresselinje3 == null)?this.adresselinje3 = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "adresselinje3"):this.adresselinje3);
        }

        public com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>> land() {
            return ((this.land == null)?this.land = new com.kscs.util.jaxb.Selector<TRoot, Selector<TRoot, TParent>>(this._root, this, "land"):this.land);
        }

    }

}
