//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 12:26:23 PM CET 
//


package no.nav.melding.virksomhet.dokumentstatusoppdatert.v1.informasjon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DokumentstatusOppdatert complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DokumentstatusOppdatert">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="journalpostId" type="{http://nav.no/melding/virksomhet/dokumentstatusOppdatert/v1/informasjon}Identifikator"/>
 *         &lt;element name="dokumentId" type="{http://nav.no/melding/virksomhet/dokumentstatusOppdatert/v1/informasjon}Identifikator"/>
 *         &lt;element name="status" type="{http://nav.no/melding/virksomhet/dokumentstatusOppdatert/v1/informasjon}Statuser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DokumentstatusOppdatert", propOrder = {
    "journalpostId",
    "dokumentId",
    "status"
})
public class DokumentstatusOppdatert {

    @XmlElement(required = true)
    protected String journalpostId;
    @XmlElement(required = true)
    protected String dokumentId;
    @XmlElement(required = true)
    protected Statuser status;

    /**
     * Gets the value of the journalpostId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournalpostId() {
        return journalpostId;
    }

    /**
     * Sets the value of the journalpostId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournalpostId(String value) {
        this.journalpostId = value;
    }

    /**
     * Gets the value of the dokumentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentId() {
        return dokumentId;
    }

    /**
     * Sets the value of the dokumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentId(String value) {
        this.dokumentId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Statuser }
     *     
     */
    public Statuser getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statuser }
     *     
     */
    public void setStatus(Statuser value) {
        this.status = value;
    }

}
