//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 12:26:23 PM CET 
//


package no.nav.melding.virksomhet.dokumentstatusoppdatert.v1.informasjon;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.nav.melding.virksomhet.dokumentstatusoppdatert.v1.informasjon package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DokumentstatusOppdatert_QNAME = new QName("http://nav.no/melding/virksomhet/dokumentstatusOppdatert/v1/informasjon", "dokumentstatusOppdatert");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.nav.melding.virksomhet.dokumentstatusoppdatert.v1.informasjon
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DokumentstatusOppdatert }
     * 
     */
    public DokumentstatusOppdatert createDokumentstatusOppdatert() {
        return new DokumentstatusOppdatert();
    }

    /**
     * Create an instance of {@link Statuser }
     * 
     */
    public Statuser createStatuser() {
        return new Statuser();
    }

    /**
     * Create an instance of {@link Kodeverdi }
     * 
     */
    public Kodeverdi createKodeverdi() {
        return new Kodeverdi();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DokumentstatusOppdatert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nav.no/melding/virksomhet/dokumentstatusOppdatert/v1/informasjon", name = "dokumentstatusOppdatert")
    public JAXBElement<DokumentstatusOppdatert> createDokumentstatusOppdatert(DokumentstatusOppdatert value) {
        return new JAXBElement<DokumentstatusOppdatert>(_DokumentstatusOppdatert_QNAME, DokumentstatusOppdatert.class, null, value);
    }

}
