//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.simpletypes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SivilstandTypeKode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SivilstandTypeKode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="EKTEFELLE"/&gt;
 *     &lt;enumeration value="ENKE"/&gt;
 *     &lt;enumeration value="ENSLIG"/&gt;
 *     &lt;enumeration value="FELLES-BARN"/&gt;
 *     &lt;enumeration value="FORELDER"/&gt;
 *     &lt;enumeration value="GIFT"/&gt;
 *     &lt;enumeration value="PARTNER"/&gt;
 *     &lt;enumeration value="SAMBOER1-5"/&gt;
 *     &lt;enumeration value="SAMBOER3-2"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SivilstandTypeKode", namespace = "http://nav.no/dok/brevdata/felles/v1/SimpleTypes")
@XmlEnum
public enum SivilstandTypeKode {


    /**
     * Ektefelle
     * 
     */
    EKTEFELLE("EKTEFELLE"),

    /**
     * Enke
     * 
     */
    ENKE("ENKE"),

    /**
     * Enslig
     * 
     */
    ENSLIG("ENSLIG"),

    /**
     * Felles barn
     * 
     */
    @XmlEnumValue("FELLES-BARN")
    FELLES_BARN("FELLES-BARN"),

    /**
     * Forelder
     * 
     */
    FORELDER("FORELDER"),

    /**
     * Gift
     * 
     */
    GIFT("GIFT"),

    /**
     * Partner
     * 
     */
    PARTNER("PARTNER"),

    /**
     * Samboer
     * 
     */
    @XmlEnumValue("SAMBOER1-5")
    SAMBOER_1_5("SAMBOER1-5"),

    /**
     * Samboer
     * 
     */
    @XmlEnumValue("SAMBOER3-2")
    SAMBOER_3_2("SAMBOER3-2");
    private final String value;

    SivilstandTypeKode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SivilstandTypeKode fromValue(String v) {
        for (SivilstandTypeKode c: SivilstandTypeKode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
