//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.14 at 02:19:20 PM CEST 
//


package v1.simpletypes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Spraakkode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Spraakkode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="NN"/&gt;
 *     &lt;enumeration value="EN"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Spraakkode", namespace = "http://nav.no/dok/brevdata/felles/v1/SimpleTypes")
@XmlEnum
public enum Spraakkode {

    NB,
    NN,
    EN;

    public String value() {
        return name();
    }

    public static Spraakkode fromValue(String v) {
        return valueOf(v);
    }

}
