name: Build and test artifact - create draft if main branch

on:
  push:
    branches:
      - '**'

jobs:
  build:
    uses: navikt/dok-workflows/.github/workflows/build-artifact.yml@main
    permissions:
      contents: read
      pull-requests: read
    with:
      java-version: '17'
    secrets: inherit
