name: Build and test artifact - create draft if main branch

on:
  push:
    branches:
      - '**'

jobs:
  build-main-and-feature-branch:
    permissions:
      pull-requests: write
      contents: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-main.yml@main
    with:
      java-version: '17'
    secrets: inherit
